title: Sprite's Journey Blog
description: Software development, projects, and things I'm learning in the big wide world.
author: Sam Smith | Spriteful Solutions

url: ""
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

#site information such as title, description, and author can be changed here
#as well as links and site setup. For more information, see https://jekyllrb.com/docs/configuration/