title: Sam's BlogHub
description: A blog about programming, writing, and personal experiences.
author: Samantha Smith

url:
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

markdown:kramdown

defaults:
  - scope:
    path: ""
    type: "posts"
    
    values:
    layout: "post"